- hosts: "{{ hosts }}" 
  roles:
  - role: docker
  - role: dnsmasq

- hosts: "{{ hosts }}"
  roles:
  - role: consul
    consul_servers:
    - "{{ ansible_eth0.ipv4.address }}" 
    consul_is_server: true
    consul_client_address_bind: true
    consul_datacenter: dc2
    consul_acl_datacenter: dc2
    tags: consul
  - role: nomad
    nomad_servers:
    - "{{ ansible_eth0.ipv4.address }}"
