- hosts: localhost
  tasks:
    - get_url:
         url: "{{ nexus_url }}/{{ item }}.json"
         url_password: "{{ nexus_password }}"
         url_username: "{{ nexus_username }}"
         dest: /tmp/{{ item }}.json
      with_items:
        - service
        - deployment
        - routes

    - shell: docker cp /tmp/{{ item }}.json consul:/tmp && docker exec consul consul kv import @/tmp/{{ item }}.json
      with_items:
        - service
        - deployment
        - routes
