---
  - name: install packages
    apt:
      name: "{{ item }}"
      update_cache: yes
      state: latest
      install_recommends: no
    with_items:
      - python-pip

  - name: Install Docker-Py
    pip: name=docker-py state=present
