---
# File: tasks/install.yml - package installation tasks for Nomad

- name: OS packages
  package: "name={{ item }} state=present"
  with_items: "{{ nomad_os_packages }}"
  tags: installation

- name: Check Nomad package checksum file
  become: no
  connection: local
  stat: "path={{ tmp_dir }}/nomad_{{ nomad_version }}_SHA256SUMS"
  run_once: true
  register: nomad_checksum

- name: Get Nomad package checksum file
  become: no
  connection: local
  get_url: "url={{ nomad_checksum_file_url }} dest={{ tmp_dir }}/nomad_{{ nomad_version }}_SHA256SUMS"
  run_once: true
  tags: installation
  when: nomad_checksum.stat.exists == False

- name: Get nomad package checksum
  become: no
  connection: local
  shell: "grep {{ nomad_pkg }} {{ tmp_dir }}/nomad_{{ nomad_version }}_SHA256SUMS"
  run_once: true
  register: nomad_sha256
  tags: installation

- name: Check Nomad package file
  become: no
  connection: local
  stat: "path={{ tmp_dir }}/{{ nomad_pkg }}"
  run_once: true
  register: nomad_package

- name: Download nomad
  become: no
  connection: local
  get_url: "url={{ nomad_zip_url }} dest={{ tmp_dir }}/{{ nomad_pkg }} checksum=sha256:{{ nomad_sha256.stdout.split(' ')|first }} timeout=42"
  run_once: true
  tags: installation

- name: Unarchive nomad
  become: no
  connection: local
  unarchive: "src={{ tmp_dir }}/{{ nomad_pkg }} dest={{ tmp_dir }} creates={{ tmp_dir }}/nomad remote_src=True"
  run_once: true
  tags: installation

- name: Install nomad
  copy: "src={{ tmp_dir }}/nomad dest=/usr/local/bin/ owner={{ nomad_user }} group={{ nomad_group }} mode=0755"
  tags: installation

- name: Cleanup
  become: no
  connection: local
  file: "dest={{ tmp_dir }}/nomad state=absent"
  run_once: true
  tags: installation
